appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c329eef87b5930700c32c48
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: gggyL2Pq8Okfy7J//smfbPoLIMKok5lqubnme9tZp379xL5GRUk6CjDRpDmIrdcSMCIwmdepTizPJzvUs95aBDkN9pZPS218PVqkNWaBWgUe5aLZRIQPx4xUd8P7oZEwjNRB7F6EaP58yeDgX46iJAfQ6NJyRCwPWIM0Fy+4cSkQb3AizDkSOAJ0XFjO5VW5T6qfM+oh0SDjSn5BXrI3f2oLN6W/S7j2gkNNxjU+WkpY6S7wWhxuorTP4e0Hz5zLx1Rj2qiflgIIdvOcySJiO/5Otx4nJAEC2ExPU2cE1O9meDNklRjRQCFTJmt+CjySXInflNKRzuqifGlIqRSuEdg6rqdIlLvaxlp3Y089EEygJblUaq9C+8kj18OTO4TlfVnOw4Ir7qqHjMx+7Q78xNFklF7xhN2assa+RNrSgZC+9pw9//3jmjT5uFdOdxeqEbX3t5K8/3ZWO0pX+/0VbsfdDgQKyx6v25qFdSXnSUqsIBHb3Dm2gkdDnbMZAT0BJDnJO+4L6i8C6dHHBfZ9Zn84izV1btZTeEGKCnBnh+3palZph87xNjmUJkIezrXKMNNw3vPUYLX723TWTWdA3oVKwJor2s6I1IUjge2W8kF6wcnmj9wFQMufF2pNKRB+cNWEBY42lMoIIz02MZVeQtINNbpu0JKOsPfPn61HqPw=}
